### ISSUE TITLE
Type does not exist after upgrade from 1.9.1 on API root

### ISSUE THREAD

**Issue by wills01** [auth0/nextjs-auth0#1050]
### Checklist

- [X] The issue can be reproduced in the [sample app](https://github.com/auth0-samples/auth0-nextjs-samples/tree/main/Sample-01) (or N/A).
- [X] I have looked into the [README](https://github.com/auth0/nextjs-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

unable to build get error

Property 'user' does not exist on type 'Promise<Session | null | undefined>'

### Reproduction

1. create ts file in API folder
2. add the following

 ```js
import { NextApiRequest, NextApiResponse } from 'next';
import { withApiAuthRequired, getSession } from '@auth0/nextjs-auth0'
import { addAircraft, deleteAircraft, updateAircraft } from '../../../utils/aircraft';
import {  getUser } from "../../../utils/user";
export default withApiAuthRequired(async (req: NextApiRequest, res: NextApiResponse) => {
    const session = getSession(req, res);
    const user = session.user.sub
```

get the following error when building:

Property 'user' does not exist on type 'Promise<Session | null | undefined>

### SDK version

2.2.1, but fails for > 1.9.2

### Next.js version

12.3.4

### Node.js version

16.14.2

**Comment by adamjmcgrath** [comment]
HI @wills01 - thanks for raising this

`getSession` now returns a Promise, see https://github.com/auth0/nextjs-auth0/blob/main/V2_MIGRATION_GUIDE.md#getsession-now-returns-a-promise
