### ISSUE TITLE
Jest errors after upgrading to v4 SDK

### ISSUE THREAD

**Issue by backlands** [auth0/nextjs-auth0#1947]
### Checklist

- [x] The issue can be reproduced in the [nextjs-auth0 sample app](https://github.com/auth0-samples/auth0-nextjs-samples/tree/main/Sample-01) (or N/A).
- [x] I have looked into the [Readme](https://github.com/auth0/nextjs-auth0#readme), [Examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/nextjs-auth0/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [x] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [x] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [x] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [x] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

We are in the process of upgrading out application which uses Jest for testing and we are unable to get this package to play well with Jest on v4. Since Jest is a supported testing library by [Next.JS](https://nextjs.org/docs/app/building-your-application/testing/jest) I did make the assumption this library would also be compatible with Jest.

### Reproduction

1. Clone my minimal repo from the i18n example [here](https://gitlab.com/eric.klempnauer/minimal-example-jest-auth-next.js)
2. Run `npm install`
3. Run `npm run test`
4. Find error in output of `Cannot find module '@auth0/nextjs-auth0/server' from 'lib/auth0.ts'`

![Image](https://github.com/user-attachments/assets/114c5477-3ddc-4aea-862b-2564d88f52ea)

### Additional context

I have gone through some efforts to try to get this playing well with Jest and have hit a bit of a brick wall with the time I have available for this at work at the moment so wanted to get some confirmation if this is still a supported use case. I cannot at this time justify switching away from Jest as this is a fairly large project but would like the improvements from v4 of this library.

Hopeful that there may be some help here or maybe I just had the wrong combinations of things I was attempting with Jest configuration adjustments to try to get this library to map correctly. Our project is in a monorepo but testing with this minimal reproduction shows that is not the issue as the error remains the same.

Thanks for your time, hopeful that the team here can point my eyes in the right direction.

### nextjs-auth0 version

4.0.2

### Next.js version

15.2.1

### Node.js version

20.18.3

**Comment by tusharpandey13** [comment]
Hi there! Thanks for reporting this issue with Jest testing after upgrading to v4.

This is a known limitation with Jest's module resolution system when using packages that leverage the newer Node.js subpath exports feature, which we've implemented in v4.

The simplest fix is to update your Jest configuration with a moduleNameMapper that maps our subpaths:

```js
moduleNameMapper: {
  "^@auth0/nextjs-auth0/server$": "<rootDir>/node_modules/@auth0/nextjs-auth0/dist/server/index.js",
  "^@auth0/nextjs-auth0/client$": "<rootDir>/node_modules/@auth0/nextjs-auth0/dist/client/index.js",
  "^@auth0/nextjs-auth0/testing$": "<rootDir>/node_modules/@auth0/nextjs-auth0/dist/testing/index.js"
}
```

Alternatively, you can use the `jest-transform-stub` package to mock the imports.

We're considering adding a testing configuration example in our documentation to help others with this transition. Please let us know if this solution works for your setup!

**Comment by backlands** [comment]
That did the trick, though with working with Next.JS I had to go another step further and add custom `transformIgnorePatterns` after the async jest configuration is finished by Next.JS. A full working example of this can be found in my reproduction repo, the diff is [here](https://gitlab.com/eric.klempnauer/minimal-example-jest-auth-next.js/-/commit/dc9daa1c396825c4e2d899ab537e148ff66adbb4).

Feel free to use this for a `with-jest` example. I am technically supposed to be off work today so jumped on quickly to see what I was missing as I had tried this earlier yesterday! Luckily with the addition of what is below did the trick with Next.JS!

```ts
import type { Config } from 'jest'
import nextJest from 'next/jest.js'

const createJestConfig = nextJest({
  // Provide the path to your Next.js app to load next.config.js and .env files in your test environment
  dir: './',

})

// Add any custom config to be passed to Jest
const config: Config = {
  coverageProvider: 'v8',
  testEnvironment: 'jsdom',
  // If working in a monorepo these paths may need to be adjusted to go up the directory tree to
  // your project root to point to the root `node_modules`: `<rootDir>/../../node_modules`
  moduleNameMapper: {
    "^@auth0/nextjs-auth0/server$": "<rootDir>/node_modules/@auth0/nextjs-auth0/dist/server/index.js",
    "^@auth0/nextjs-auth0/client$": "<rootDir>/node_modules/@auth0/nextjs-auth0/dist/client/index.js",
    "^@auth0/nextjs-auth0/testing$": "<rootDir>/node_modules/@auth0/nextjs-auth0/dist/testing/index.js"
  },
}

const configuration = async () => ({
  ...(await createJestConfig(config)()),
  transformIgnorePatterns: [
    // The regex below is just a guess, you might tweak it
    "/node_modules/(?!(@auth0/nextjs-auth0|oauth4webapi)/)",
    "\\.pnp\\.[^\\\/]+$",
  ]
})

// createJestConfig is exported this way to ensure that next/jest can load the Next.js config which is async
export default configuration

```

**Comment by tusharpandey13** [comment]
Great to know that it worked and thanks for the code! We'll make sure to document this soon.
Have a nice day!
